[package]
name = "rir"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "^5.5.1"
rand = "0.9.1"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.22"
once_cell = "1.21.3"
notify = "8.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
